# Generated by Django 3.2.8 on 2021-12-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tulips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tulip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tulips.tulips', verbose_name='тюльпан'),
        ),
    ]
