# Generated by Django 3.2.8 on 2021-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulips', '0002_alter_rating_tulip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=300, verbose_name='Ф.И.О.')),
                ('contacts', models.CharField(max_length=20, verbose_name='Телефон')),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
